etl_pipeline:
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: warehouse
      schema: public
      threads: 4
      keepalives_idle: 0
      search_path: "public"
    
    prod:
      type: trino
      method: none
      host: trino
      port: 8080
      catalog: postgresql
      schema: warehouse
      threads: 4
      http_scheme: http
      
  target: dev