version: '3.8'
services:
  consumer:
    build: .
    container_name: consumer_service
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=etl_events
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=etl-raw
    depends_on:
      - kafka
      - minio
    ports:
      - "8001:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8001
